// Code generated by goctl. DO NOT EDIT.
// Source: mooon_login.proto

package server

import (
	"context"

	"mooon-gateway/internal/logic"
	"mooon-gateway/internal/svc"
	"mooon-gateway/pb/mooon_login"
)

type MooonLoginServer struct {
	svcCtx *svc.ServiceContext
	mooon_login.UnimplementedMooonLoginServer
}

func NewMooonLoginServer(svcCtx *svc.ServiceContext) *MooonLoginServer {
	return &MooonLoginServer{
		svcCtx: svcCtx,
	}
}

func (s *MooonLoginServer) Login(ctx context.Context, in *mooon_login.LoginReq) (*mooon_login.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
