// Code generated by goctl. DO NOT EDIT.
// Source: mooon_auth.proto

package server

import (
	"context"

	"mooon-gateway/internal/logic"
	"mooon-gateway/internal/svc"
	"mooon-gateway/pb/mooon_auth"
)

type MooonAuthServer struct {
	svcCtx *svc.ServiceContext
	mooon_auth.UnimplementedMooonAuthServer
}

func NewMooonAuthServer(svcCtx *svc.ServiceContext) *MooonAuthServer {
	return &MooonAuthServer{
		svcCtx: svcCtx,
	}
}

func (s *MooonAuthServer) Authenticate(ctx context.Context, in *mooon_auth.AuthReq) (*mooon_auth.AuthResp, error) {
	l := logic.NewAuthenticateLogic(ctx, s.svcCtx)
	return l.Authenticate(in)
}
