// Code generated by goctl. DO NOT EDIT.
// Source: mooon_auth.proto

package mooonauth

import (
	"context"

	"mooon-gateway/pb/mooon_auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReq  = mooon_auth.AuthReq
	AuthResp = mooon_auth.AuthResp
	Cookie   = mooon_auth.Cookie

	MooonAuth interface {
		Authenticate(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
	}

	defaultMooonAuth struct {
		cli zrpc.Client
	}
)

func NewMooonAuth(cli zrpc.Client) MooonAuth {
	return &defaultMooonAuth{
		cli: cli,
	}
}

func (m *defaultMooonAuth) Authenticate(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	client := mooon_auth.NewMooonAuthClient(m.cli.Conn())
	return client.Authenticate(ctx, in, opts...)
}
