// Written by yijian on 2024/01/21

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: mooon_login.proto

package mooon_login

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MooonLogin_Login_FullMethodName = "/mooon_login.MooonLogin/Login"
)

// MooonLoginClient is the client API for MooonLogin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MooonLoginClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
}

type mooonLoginClient struct {
	cc grpc.ClientConnInterface
}

func NewMooonLoginClient(cc grpc.ClientConnInterface) MooonLoginClient {
	return &mooonLoginClient{cc}
}

func (c *mooonLoginClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, MooonLogin_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MooonLoginServer is the server API for MooonLogin service.
// All implementations must embed UnimplementedMooonLoginServer
// for forward compatibility
type MooonLoginServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	mustEmbedUnimplementedMooonLoginServer()
}

// UnimplementedMooonLoginServer must be embedded to have forward compatible implementations.
type UnimplementedMooonLoginServer struct {
}

func (UnimplementedMooonLoginServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMooonLoginServer) mustEmbedUnimplementedMooonLoginServer() {}

// UnsafeMooonLoginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MooonLoginServer will
// result in compilation errors.
type UnsafeMooonLoginServer interface {
	mustEmbedUnimplementedMooonLoginServer()
}

func RegisterMooonLoginServer(s grpc.ServiceRegistrar, srv MooonLoginServer) {
	s.RegisterService(&MooonLogin_ServiceDesc, srv)
}

func _MooonLogin_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MooonLoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MooonLogin_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MooonLoginServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MooonLogin_ServiceDesc is the grpc.ServiceDesc for MooonLogin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MooonLogin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mooon_login.MooonLogin",
	HandlerType: (*MooonLoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MooonLogin_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mooon_login.proto",
}
